#!/usr/bin/env bash
# ============================================================
# setup_udev.sh — ล็อก USB port สำหรับ ESP32 และ YDLiDAR X3 Pro
# วิธีใช้: sudo bash setup_udev.sh
#
# เหตุผลที่ใช้ physical path แทน serial number:
# ทั้ง ESP32 และ LiDAR ใช้ CP210x ที่มี SerialNumber="0001" เหมือนกัน
# จึงต้อง lock ด้วย physical USB port (ตำแหน่งขาปลั๊ก)
# ============================================================

set -e

echo "=== AMR USB Port Lock Setup ==="
echo ""

# -------- ตรวจสอบสิทธิ์ --------
if [[ $EUID -ne 0 ]]; then
  echo "[ERROR] กรุณารันด้วย sudo: sudo bash $0"
  exit 1
fi

# -------- ตรวจสอบ device ที่ต่ออยู่ --------
echo "[INFO] กำลังค้นหา CP210x USB devices..."
echo ""

DEVICES=$(ls /sys/bus/usb/devices/*/product 2>/dev/null | xargs grep -l "CP2102" 2>/dev/null | sed 's|/product||' | xargs -I{} basename {} || true)

if [[ -z "$DEVICES" ]]; then
  echo "[ERROR] ไม่พบ CP210x device กรุณาเสียบ ESP32 และ LiDAR ก่อน"
  exit 1
fi

echo "พบ CP210x devices:"
echo "------------------------------------------------------------"
for dev_path in /sys/bus/usb/devices/*/product; do
  product=$(cat "$dev_path" 2>/dev/null || "")
  if echo "$product" | grep -q "CP2102"; then
    dev_dir=$(dirname "$dev_path")
    usb_name=$(basename "$dev_dir")
    tty=""
    for f in "$dev_dir"/*/tty/tty*; do
      tty=$(basename "$f" 2>/dev/null) && break
    done
    echo "  USB Path: $usb_name  →  /dev/$tty"
  fi
done
echo "------------------------------------------------------------"
echo ""

# -------- ถาม user ว่า path ไหนคือ ESP32 --------
echo "จาก dmesg ของคุณ:"
echo "  ESP32  → ต่อ USB port ที่ให้ ttyUSB0  (USB path: 7-2.2)"
echo "  LiDAR  → ต่อ USB port ที่ให้ ttyUSB1  (USB path: 7-2.4)"
echo ""
echo "คำเตือน: ถ้า USB path ไม่ตรง กรุณาแก้ไขตัวเลขด้านล่างก่อน reload"
echo ""

# -------- ดึง USB path จากระบบจริง --------
detect_usb_path() {
  local tty_name="$1"  # เช่น ttyUSB0
  local dev_link="/sys/class/tty/${tty_name}/device"
  if [[ -e "$dev_link" ]]; then
    # ดึง USB path เช่น "7-2.2:1.0" → "7-2.2"
    local full=$(readlink -f "$dev_link")
    # path เช่น /sys/devices/pci.../usb7/7-2/7-2.2/7-2.2:1.0/...
    echo "$full" | grep -oP '\d+-\d+(\.\d+)+(?=:\d+\.\d+)' | tail -1
  fi
}

ESP32_PATH=$(detect_usb_path "ttyUSB0")
LIDAR_PATH=$(detect_usb_path "ttyUSB1")

if [[ -z "$ESP32_PATH" ]] || [[ -z "$LIDAR_PATH" ]]; then
  echo "[WARN] ไม่สามารถตรวจจับ USB path อัตโนมัติ ใช้ค่า default จาก dmesg"
  ESP32_PATH="7-2.2"
  LIDAR_PATH="7-2.4"
fi

echo "[INFO] ESP32 USB path: $ESP32_PATH"
echo "[INFO] LiDAR  USB path: $LIDAR_PATH"
echo ""

# -------- เขียน udev rules --------
RULES_FILE="/etc/udev/rules.d/99-amr-usb.rules"
cat > "$RULES_FILE" << EOF
# AMR USB Port Lock Rules
# Generated by setup_udev.sh
# Lock โดยใช้ physical USB port path (ไม่ใช้ serial number เพราะ both = "0001")

# ESP32 Motor Controller
SUBSYSTEM=="tty", DEVPATH=="*${ESP32_PATH}*", SYMLINK+="esp32", GROUP="dialout", MODE="0666", TAG+="udev-acl"

# YDLiDAR X3 Pro
SUBSYSTEM=="tty", DEVPATH=="*${LIDAR_PATH}*", SYMLINK+="lidar", GROUP="dialout", MODE="0666", TAG+="udev-acl"
EOF

echo "[OK] เขียน udev rules ไปที่: $RULES_FILE"
cat "$RULES_FILE"
echo ""

# -------- เพิ่ม user เข้า dialout group --------
CURRENT_USER=${SUDO_USER:-$(whoami)}
usermod -a -G dialout "$CURRENT_USER"
echo "[OK] เพิ่ม user '$CURRENT_USER' เข้า group 'dialout'"
echo ""

# -------- Reload udev --------
udevadm control --reload-rules
udevadm trigger
echo "[OK] Reload udev rules แล้ว"
echo ""
echo "=== Done! ==="
echo ""
echo "ถอดแล้วเสียบ USB ใหม่ แล้วตรวจสอบด้วย:"
echo "  ls -la /dev/esp32 /dev/lidar"
echo ""
echo "ถ้าเห็น symlink แสดงว่าสำเร็จ:"
echo "  /dev/esp32  -> ttyUSBx"
echo "  /dev/lidar  -> ttyUSBy"
