; PlatformIO Project Configuration
; AMR ESP32 Motor Controller
; Board: ESP32 Dev Module

[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_filters = send_on_enter, default
; Serial monitor (USB port - จะถูกระบุใหม่หลังทำ udev rule)
monitor_speed = 115200
upload_speed  = 921600

; Libraries
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.5

; Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_ARDUHAL_LOG_DEFAULT_LEVEL=0
